### ISSUE TITLE
Sync problem?

### ISSUE THREAD

**Issue by Sblop** [Bleala/Vdirsyncer-DOCKERIZED#1]
Hi, Thanks for the updated docker image. This is great!
However I have one small problem. It seels only discovery runs, eventhough I have set the flag to true.

Docker composer: 
```
vdirsyncer:
 # image: pschlieker/vdirsyncer-docker
    image: bleala/vdirsyncer:latest
    container_name: vdirsyncer
    volumes:
      - "/share/Docker/vdirsyncer:/vdirsyncer" 
      - "/share/Docker/vdirsyncer/config:/vdirsyncer/config"
      
      - "/etc/localtime:/etc/localtime:ro"  
    environment: 
      - CRON_TIME=0 */1 * * *
      - AUTODISCOVER=true
      - AUTOSYNC=true
    restart: unless-stopped
    networks:
      docker_frontend:

```
In the log it confirms the correct piece of the script is running:

Starting Logging...

```
Autodiscover and Autosync are enabled


crond: crond (busybox 1.33.1) started, log level 8


crond: USER root pid  92 cmd run-parts /etc/periodic/15min


crond: USER root pid 200 cmd run-parts /etc/periodic/15min


crond: USER root pid 296 cmd run-parts /etc/periodic/15min


crond: USER root pid 402 cmd run-parts /etc/periodic/15min


crond: USER root pid 403 cmd run-parts /etc/periodic/hourly


crond: USER root pid 404 cmd yes | vdirsyncer discover && vdirsyncer metasync && vdirsyncer sync
```

It runs the discovery, however not the meta or the sync?

After the discovery has run (I will not post the log as this contains personal names etc.) this happens.

```
error: 1 out of 11 tasks failed.


crond: USER root pid 512 cmd run-parts /etc/periodic/15min


crond: USER root pid 616 cmd run-parts /etc/periodic/15min


crond: USER root pid 716 cmd run-parts /etc/periodic/15min


crond: USER root pid 820 cmd run-parts /etc/periodic/15min


crond: USER root pid 821 cmd run-parts /etc/periodic/hourly


crond: USER root pid 822 cmd yes | vdirsyncer discover && vdirsyncer metasync && vdirsyncer sync
```

Same problem over again...

The error is due to a sync problem with sogo, so I would not expect this to be a problem?

It doesnt seem like this is correct behaviour?
