### ISSUE TITLE
Make GID/UID settable via parameter (again)

### ISSUE THREAD

**Issue by threshold68** [Bleala/Vdirsyncer-DOCKERIZED#20]
It seems that GID and UID of the vdirsyncer user were changeable via corresponding parameters e.g. in the docker-compose.yml file but this possibility was removed in version 2.4.1. Since version 2.4.1 GID and UID are fixed to 1000.

This creates files permission problems when using vdirsyncer with local filesystem type storage e.g. on Syology NAS where UID 1000 is not permitted.

Currently, I need to patch the UID and GID in the Dockerfile to the UID/GID of the local Synology user that uses the local filesystem type CALDAV storage.

This could be avoided, if the GID an UID were made settable via parameters in the docker-compose file as it presumably was the case before version 2.4.1. This would be my change request.

BR/Harald

**Comment by Bleala** [comment]
Hello @threshold68 

I did this to drop the root privileges from the container completely, is it possible, that you use docker volumes instead?
With them you don't have the file permission problems.

Greetings

**Comment by threshold68** [comment]
Hi @Bleala ,

as said above, II am using vdirsyncer to sync local files on a Synology NAS outside the part of the file system that is managed by docker and owned by a different user than the docker user. 

Therefore, I don't see a way how this can by accomplished by using docker volumes.

BR

**Comment by Bleala** [comment]
Hi @threshold68 

Could you try setting the `user` in the docker-compose.yaml?

Like this:

```
services:
  app:
    image: bleala/vdirsyncer:latest
    container_name: vdirsyncer
    restart: unless-stopped
    user: "your_UID:your_GID"
```

Set it to the UID/GID of your Synology DSM user, maybe this could work.

Greetings

**Comment by szonov** [comment]
> Hi [@threshold68](https://github.com/threshold68)
> 
> Could you try setting the `user` in the docker-compose.yaml?
> 
> Like this:
> 
> ```
> services:
>   app:
>     image: bleala/vdirsyncer:latest
>     container_name: vdirsyncer
>     restart: unless-stopped
>     user: "your_UID:your_GID"
> ```
> 
> Set it to the UID/GID of your Synology DSM user, maybe this could work.
> 
> Greetings

With AUTOSYNC=true and defining user inside docker compose file  I've got a permission denied error for writing to `/etc/crontabs/vdirsyncer` file (since in Dockerfile permissions set to 644).
To fix this problem I just redefine `CRON_FILE` env to file writable by my user. By the way, also on Synology DSM.
my docker compose looks like:
```
services:
  app:
    image: bleala/vdirsyncer:latest
    container_name: vdirsyncer
    restart: unless-stopped
    user: 1026:100
    volumes:
      - ./data:/vdirsyncer
    environment:
      - AUTOSYNC=true
      - CRON_TIME=05 * * * *
      - CRON_FILE=/vdirsyncer/crontab.txt
```

If @Bleala will change permissions from 644 to 666 on line 153 in Dockerfile, then this fix will not require. I mean
change:
```
&& chmod 644 "${CRON_FILE}" \
```
to:
```
&& chmod 666 "${CRON_FILE}" \
```
