### ISSUE TITLE
trouble mounting config file

### ISSUE THREAD

**Issue by jill88** [Bleala/Vdirsyncer-DOCKERIZED#34]
I think (I'm not sure) I am having trouble mounting the config file because it doesn't have an extension.  I feel docker compose keeps treating it as a folder, but it's just a file.  Am I misunderstanding something?  I have tried every which way, thanks.  Here is my compose file.  Whenever I start the container, it just exits saying it can't create the log file, but I think it is not reading the config file at all.

```
networks:
  default:
    driver: bridge
volumes:
  vdirsyncer:
    name: vdirsyncer
    driver: local
services:
  # Vdirsyncer - sync calendars and addressbooks between servers and the local filesystem. DOCKERIZED!
  # https://hub.docker.com/r/bleala/vdirsyncer
  app:
    image: bleala/vdirsyncer:latest
    container_name: vdirsyncer
    restart: unless-stopped
    networks:
      - default
    environment:
      - TZ=America/Los_Angeles # set your timezone, for correct container and log time, default to Europe/Vienna
      - AUTODISCOVER= # set to true for automatic discover, default to false
      - AUTOSYNC= # set to true for automatic sync, default to false
      - AUTOUPDATE= # set to true for automatic Vdirsyncer and dependencies updates on container startup, default to false
      - CRON_TIME= # adjust autosync /-discover time, default to 15 minutes - */15 * * * * 
      - POST_SYNC_SCRIPT_FILE= # optional,  set to script path to automatically run your custom script after the cronjob `vdirsyncer` command(s), default to nothing
      - LOG= # optional, default to /vdirsyncer/vdirsyncer.log
      - LOG_LEVEL= # optional, default is normal output from supercronic
    volumes:
      - vdirsyncer:/vdirsyncer # Docker Volume
      - ./config:/vdirsyncer/config # Vdirsyncer Config
      # Optional
      # - /path/to/custom_script.sh:/vdirsyncer/custom_script.sh  # Custom Script

```
